- name: ファイアウォール設定
  lineinfile: dest=/etc/sysconfig/iptables
    regexp="^-A INPUT -p {{item.protocol}} -m {{item.protocol}} --dport {{item.port}} -j ACCEPT$"
    line="-A INPUT -p {{item.protocol}} -m {{item.protocol}} --dport {{item.port}} -j ACCEPT"
    insertafter="^:OUTPUT ACCEPT \[\d*:\d*\]$"
  with_items:
    - { protocol: tcp, port: 80 }
    - { protocol: tcp, port: 443 }
    - { protocol: tcp, port: 389 }
    - { protocol: tcp, port: 636 }
    - { protocol: tcp, port: 88 }
    - { protocol: tcp, port: 464 }
    - { protocol: tcp, port: 53 }
    - { protocol: udp, port: 88 }
    - { protocol: udp, port: 464 }
    - { protocol: udp, port: 53 }
    - { protocol: udp, port: 123 }

- name: ファイアウォール再起動
  action: service name=iptables state=restarted
