- name: rubyが既にインストールされていないかチェック
  shell: rbenv versions | grep {{ version }} | tr '*' ' ' | sed -e 's/\s\+//' | cut -f1 -d' '
  register: ruby_is_installed
  environment:
    RBENV_ROOT: "{{ rbenv_root }}"
    PATH: "{{ bin_path }}"

- name: rubyインストール
  shell: rbenv install {{ version }}
  async: 12000
  poll: 60
  when: ruby_is_installed.stdout == ""
  environment:
    RBENV_ROOT: "{{ rbenv_root }}"
    PATH: "{{ bin_path }}"

- name: rbenv再読み込み
  shell: rbenv rehash
  when: ruby_is_installed.stdout == ""
  environment:
    RBENV_ROOT: "{{ rbenv_root }}"
    PATH: "{{ bin_path }}"

- name: rbenvコンフィグ
  shell: rbenv global {{ version }}
  when: ruby_is_installed.stdout == ""
  environment:
    RBENV_ROOT: "{{ rbenv_root }}"
    PATH: "{{ bin_path }}"
