- name: rubyが既にインストールされていないかチェック
  shell: RBENV_ROOT=/home/{{ ruby_dep_user }}/.rbenv /home/{{ ruby_dep_user }}/.rbenv/bin/rbenv versions | grep {{ version }} | tr '*' ' ' | sed -e 's/\s\+//' | cut -f1 -d' '
  register: ruby_is_installed

- name: rubyインストール
  shell: RBENV_ROOT=/home/{{ ruby_dep_user }}/.rbenv /home/{{ ruby_dep_user }}/.rbenv/bin/rbenv install {{ version }}
  async: 12000
  poll: 60

- name: rbenv再読み込み
  shell: RBENV_ROOT=/home/{{ ruby_dep_user }}/.rbenv /home/{{ ruby_dep_user }}/.rbenv/bin/rbenv rehash

- name: rbenvコンフィグ
  shell: RBENV_ROOT=/home/{{ ruby_dep_user }}/.rbenv /home/{{ ruby_dep_user }}/.rbenv/bin/rbenv global {{ version }}
