- name: vimのアンインストール
  yum: name=vim state=absent
  tags:
      - vim

- name: vimのソース取得
  get_url: url=ftp://ftp.vim.org/pub/vim/unix/vim-7.4.tar.bz2 dest=/usr/local/src/vim-7.4.tar.bz2 mode=0777

- name: vimのソース解凍
  unarchive: src=/usr/local/src/vim-7.4.tar.bz2 dest=/usr/local/src
  tags:
      - vim

- name: vimのコンフィグ
  command: chdir=/usr/local/src/vim74 ./configure --enable-multibyte --with-features=huge --enable-luainterp --enable-perlinterp --enable-pythoninterp --with-python-config-dir=/usr/lib/python2.6/config --enable-rubyinterp --with-ruby-command=/usr/bin/ruby
  tags:
      - vim

- name: vimのMake
  command: chdir=/usr/local/src/vim74 make
  tags:
      - vim

- name: vimのInstall
  command: chdir=/usr/local/src/vim74 make install
  tags:
      - vim

- name: 設定ファイルダウンロード
  git: repo=https://github.com/pater4/vim.git
    dest=/home/vagrant/vim
  tags:
      - vim

- name: 設定ファイル権限変更
  file: path=/home/vagrant/vim state=directory recurse=yes owner=vagrant group=vagrant mode=0777
  tags:
      - vim

- name: 設定ファイルルーティング
  action: copy src=_vimrc dest=/home/vagrant/_vimrc owner=vagrant group=vagrant mode=0755
  tags:
      - vim

- name: vim用のごみ箱作成
  file: path=/home/vagrant/.vimfiler_trashbox state=directory owner=vagrant group=vagrant mode=0777
  tags:
      - vim
