---
- hosts: flyerserver
  remote_user: vagrant
  sudo: yes
  tasks:
  - name: パッケージのインストール
    yum: name={{ item }} state=latest
    with_items:
      - python
      - python-pip
      - samba

  - name: pythonのライブラリインストール
    pip: name={{ item }} state=latest
    with_items:
      - pillow
